/**
 * Auto-generated chain icon mapping
 * Source: TrustWallet Assets & Fallbacks
 * Generated by: scripts/download-icons-hq.ts
 */

export const CHAIN_ICONS: Record<string, string> = {
  "Ethereum": "/chains/ethereum.png",
  "Solana": "/chains/solana.png",
  "Bitcoin": "/chains/bitcoin.png",
  "Base": "/chains/base.png",
  "Tron": "/chains/tron.png",
  "Plasma": "/chains/plasma.png",
  "Arbitrum": "/chains/arbitrum.png",
  "Polygon": "/chains/polygon.png",
  "Ink": "/chains/ink.png",
  "Aptos": "/chains/aptos.png",
  "Katana": "/chains/katana.png",
  "Mantle": "/chains/mantle.png",
  "Starknet": "/chains/starknet.png",
  "Scroll": "/chains/scroll.png",
  "Monad": "/chains/monad.png",
  "Flare": "/chains/flare.png",
  "Linea": "/chains/linea.png",
  "Berachain": "/chains/berachain.png",
  "Near": "/chains/near.png",
  "Gnosis": "/chains/gnosis.png",
  "Sei": "/chains/sei.png",
  "Unichain": "/chains/unichain.png",
  "TON": "/chains/ton.png",
  "Sonic": "/chains/sonic.png",
  "Flow": "/chains/flow.png",
  "Mezo": "/chains/mezo.png",
  "Celo": "/chains/celo.png",
  "Abstract": "/chains/abstract.png",
  "Ronin": "/chains/ronin.png",
  "opBNB": "/chains/opbnb.png",
  "Kaia": "/chains/kaia.png",
  "Hemi": "/chains/hemi.png",
  "Taiko": "/chains/taiko.png",
  "Sophon": "/chains/sophon.png",
  "Fantom": "/chains/fantom.png",
  "Story": "/chains/story.png",
  "Boba": "/chains/boba.png",
  "TAC": "/chains/tac.png",
  "Somnia": "/chains/somnia.png",
  "Peaq": "/chains/peaq.png",
  "Superseed": "/chains/superseed.png",
  "Corn": "/chains/corn.png",
  "Shape": "/chains/shape.png",
  "Bnb": "/chains/bnb.png",
  "BSC": "/chains/bnb.png",
  "Binance": "/chains/bnb.png",
  "Avalanche C": "/chains/avalanche_c.png",
  "Hyperevm": "/chains/hyperevm.png",
  "Optimism": "/chains/optimism.png",
  "Plume": "/chains/plume.png",
  "Zksync": "/chains/zksync.png",
  "Worldchain": "/chains/worldchain.png",
  "Zkevm": "/chains/zkevm.png",
  "Nova": "/chains/nova.png"
};

export function getLocalChainIcon(chainName: string): string {
  // Try exact match
  if (CHAIN_ICONS[chainName]) {
    return CHAIN_ICONS[chainName];
  }

  // Try case-insensitive match
  const lowerName = chainName.toLowerCase();
  const key = Object.keys(CHAIN_ICONS).find(k => k.toLowerCase() === lowerName);
  if (key) {
    return CHAIN_ICONS[key];
  }

  return '/chains/default.png';
}
