import React from 'react';
import { format } from 'date-fns';
import { Zap, Brain } from 'lucide-react';

export interface TokenAnalysisData {
    id: string;
    aiName: string;
    createdAt: string;
    coverImage: string;
    aiJudgment: string;
    tokenSymbol: string;
    tokenChain: string;
    analysisPoints: string[];
    confidenceScore?: number;
}

interface TokenAnalysisCardProps {
    data: TokenAnalysisData;
}

export default function TokenAnalysisCard({ data }: TokenAnalysisCardProps) {
    return (
        <article className="bg-[#121212] rounded-[24px] overflow-hidden shadow-2xl mb-8 border border-white/5 mx-auto max-w-[470px]">
            {/* 1. Header: AI Identity & Time */}
            <div className="flex items-center justify-between px-4 py-3">
                <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-full bg-gradient-to-br from-cyan-400 to-blue-600 p-[1.5px]">
                        <div className="w-full h-full rounded-full bg-black flex items-center justify-center">
                            <Brain size={14} className="text-cyan-400" />
                        </div>
                    </div>
                    <div className="flex flex-col">
                        <span className="text-sm font-bold text-white leading-none">{data.aiName}</span>
                        <span className="text-[11px] text-gray-500 font-medium">
                            {format(new Date(data.createdAt), 'MMM d')} • AI Analysis
                        </span>
                    </div>
                </div>
                <div className="flex items-center gap-1.5 bg-white/5 rounded-full px-2.5 py-1">
                    <Zap size={10} className="text-yellow-400 fill-yellow-400" />
                    <span className="text-[10px] font-bold text-gray-300">{data.confidenceScore || 92}% CF</span>
                </div>
            </div>

            {/* 2. Hero Image: Abstract/Editorial */}
            <div className="relative w-full aspect-[4/5] bg-neutral-900 overflow-hidden">
                <img
                    src={data.coverImage}
                    alt="AI Analysis Visualization"
                    className="w-full h-full object-cover"
                />
                {/* Subtle inner shadow for depth */}
                <div className="absolute inset-0 shadow-[inset_0_0_40px_rgba(0,0,0,0.5)] pointer-events-none"></div>
            </div>

            {/* 3. Card Content */}
            <div className="p-5">
                {/* AI Judgment Header */}
                <div className="mb-4">
                    <h2 className="text-lg font-bold leading-snug text-white tracking-tight">
                        “{data.aiJudgment}”
                    </h2>
                </div>

                {/* Token Meta Row (Minimal) */}
                <div className="flex items-center gap-3 mb-6">
                    <span className="text-sm font-bold text-white">{data.tokenSymbol}</span>
                    <span className="h-1 w-1 rounded-full bg-gray-600"></span>
                    <span className="text-xs font-mono text-gray-400 uppercase tracking-wider border border-white/10 rounded px-1.5 py-0.5">
                        {data.tokenChain}
                    </span>
                </div>

                {/* Analysis Body (Fragmented) */}
                <div className="space-y-3 mb-6">
                    {data.analysisPoints.map((point, index) => (
                        <div key={index} className="flex gap-3 items-start group">
                            <div className="w-1 h-1 rounded-full bg-cyan-500 mt-2 shrink-0 group-hover:scale-150 transition-transform" />
                            <p className="text-sm text-gray-300 font-light leading-relaxed">
                                {point}
                            </p>
                        </div>
                    ))}
                </div>

                {/* AI Signature */}
                <div className="pt-4 border-t border-white/5 flex items-center justify-between text-[10px] text-gray-600 font-mono uppercase tracking-widest">
                    <span>Generated by KIKO Intelligence</span>
                    <span>ID: {data.id.slice(0, 8)}</span>
                </div>
            </div>
        </article>
    );
}
